# Official documentation at http://goreleaser.com
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: ks
builds:
- env:
    - CGO_ENABLED=0
  id: "ks"
  binary: ks
  goarch:
    - amd64
    - arm64
  goos:
    # - windows
    - linux
    - darwin
  hooks:
    post:
      - upx "{{ .Path }}"
  ldflags:
    - -X github.com/linuxsuren/cobra-extension/version.version={{.Version}}
    - -X github.com/linuxsuren/cobra-extension/version.commit={{.ShortCommit}}
    - -X github.com/linuxsuren/cobra-extension/version.date={{.Date}}
    - -w
- env:
    - CGO_ENABLED=0
  id: "kubectl-ks"
  binary: kubectl-ks
  main: ./kubectl-plugin/kubectl-ks.go
  goarch:
    - amd64
  goos:
    - linux
    - darwin
  hooks:
    post:
      - upx "{{ .Path }}"
  ldflags:
    - -X github.com/linuxsuren/cobra-extension/version.version={{.Version}}
    - -X github.com/linuxsuren/cobra-extension/version.commit={{.ShortCommit}}
    - -X github.com/linuxsuren/cobra-extension/version.date={{.Date}}
    - -w
dist: bin
archives:
  - name_template: "ks-{{ .Os }}-{{ .Arch }}"
    id: "ks"
    builds:
      - ks
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
  - name_template: "kubectl-ks-{{ .Os }}-{{ .Arch }}"
    id: "kubectl-ks"
    builds:
      - "kubectl-ks"
    files:
      - README.md
      - LICENSE
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  - file_name_template: >-
      ks-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}64bit
      {{- else if eq .Arch "darwin" }}macOS
      {{- else }}{{ .Arch }}{{ end -}}
    id: "ks"
    homepage: https://github.com/kubesphere-sigs/ks
    description: ks is a tool which makes it be easy to work with KubeSphere.
    maintainer: rick <rick@jenkins-zh.cn>
    license: MIT
    vendor: KubeSphere
    formats:
      - deb
      - rpm
    recommends:
      - bash-completion
      - vim
      - kubectl
    bindir: /usr/local/bin
