name: Release Drafter

on:
  push:
    branches:
      - dev-with-action

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUBLISH_SECRETS }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.6.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUBLISH_SECRETS }}
